theme: minima
title: Emma Roberts
<h1 style="font-size: 3rem; text-align: center; font-weight: bold; margin-top: 20px;">
  Emma Roberts
</h1>
description: A portfolio showcasing my projects and skills
